// AUTO-GENERATED by build_h.py — DO NOT EDIT
// 由 tools/build/crab_data.py 转换而来
#pragma once

#include <stdint.h>
#include <stddef.h>

#define CRAB_FRAME_W      200
#define CRAB_FRAME_H      100
#define CRAB_FPS          15
#define CRAB_MS_PER_FRAME 66

typedef struct {
  char id;                          // 'T' 'W' 'D' 'E' 'I'
  const uint8_t* palette;           // 512B = 256 色 RGB565 (大端)
  uint16_t intro_count;             // intro 段帧数，0 表示无 intro
  const uint8_t* const* intro_frames;
  const uint16_t* intro_sizes;
  uint16_t loop_count;              // loop 段帧数
  const uint8_t* const* loop_frames;
  const uint16_t* loop_sizes;
} CrabState;

// 调色板（512B 大端 RGB565）
extern const uint8_t T_palette[512];
extern const uint8_t W_palette[512];
extern const uint8_t D_palette[512];
extern const uint8_t E_palette[512];
extern const uint8_t I_palette[512];

// intro 帧指针 + 长度数组
extern const uint8_t* const I_intro_frames[57];
extern const uint16_t I_intro_sizes[57];

// loop 帧指针 + 长度数组
extern const uint8_t* const T_loop_frames[180];
extern const uint16_t T_loop_sizes[180];
extern const uint8_t* const W_loop_frames[48];
extern const uint16_t W_loop_sizes[48];
extern const uint8_t* const D_loop_frames[48];
extern const uint16_t D_loop_sizes[48];
extern const uint8_t* const E_loop_frames[60];
extern const uint16_t E_loop_sizes[60];
extern const uint8_t* const I_loop_frames[60];
extern const uint16_t I_loop_sizes[60];

#define CRAB_STATE_COUNT 5
extern const CrabState CRAB_STATES[CRAB_STATE_COUNT];

static inline const CrabState* crab_get_state(char c) {
  for (int i = 0; i < CRAB_STATE_COUNT; i++) {
    if (CRAB_STATES[i].id == c) return &CRAB_STATES[i];
  }
  return NULL;
}
