#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_h.py — 把 tools/build/crab_data.py 转成 ESP-IDF 固件用的 crab_data.h + crab_data.c
===========================================================================================
改编自 ClackClaw 的 build_h.py，适配 ESP32-S3 + ESP-IDF（无 Arduino 依赖）。

输出：
  main/lcd/crab_data.h  — 小型头文件：类型定义 + extern 声明 + 查表函数
  main/lcd/crab_data.c  — 大型数据文件：所有 const 数组（单独编译，避免 7MB header 拖慢编译）
"""

import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parent
BUILD   = PROJECT / "build"
sys.path.insert(0, str(BUILD))
import crab_data  # noqa: E402

OUT_H = PROJECT.parent / "main" / "lcd" / "crab_data.h"
OUT_C = PROJECT.parent / "main" / "lcd" / "crab_data.c"


def bytes_to_c_array(data: bytes, per_line: int = 16) -> str:
    """把 bytes 转成 C 数组字面量字符串"""
    if not data:
        return "  /* empty */"
    chunks = []
    for i in range(0, len(data), per_line):
        line = ", ".join(f"0x{b:02X}" for b in data[i:i+per_line])
        chunks.append("  " + line + ",")
    chunks[-1] = chunks[-1].rstrip(",")
    return "\n".join(chunks)


def emit_state_data(state: str, data: dict, out: list) -> None:
    """为单个状态输出所有数据数组定义（放进 .c 文件）"""
    pal = data["palette"]
    intro_list = data.get("intro", [])
    loop_list  = data.get("loop", [])

    out.append(f"// ============ {state} state ============")

    # palette
    out.append(f"const uint8_t {state}_palette[{len(pal)}] = {{")
    out.append(bytes_to_c_array(pal))
    out.append("};")
    out.append("")

    # intro frames
    for i, frame in enumerate(intro_list):
        out.append(f"static const uint8_t {state}_intro_f{i}[{len(frame)}] = {{")
        out.append(bytes_to_c_array(frame))
        out.append("};")
    if intro_list:
        out.append(f"const uint8_t* const {state}_intro_frames[{len(intro_list)}] = {{")
        out.append(",\n".join(f"  {state}_intro_f{i}" for i in range(len(intro_list))))
        out.append("};")
        out.append(f"const uint16_t {state}_intro_sizes[{len(intro_list)}] = {{")
        out.append("  " + ", ".join(str(len(f)) for f in intro_list))
        out.append("};")
        out.append("")

    # loop frames
    for i, frame in enumerate(loop_list):
        out.append(f"static const uint8_t {state}_loop_f{i}[{len(frame)}] = {{")
        out.append(bytes_to_c_array(frame))
        out.append("};")
    if loop_list:
        out.append(f"const uint8_t* const {state}_loop_frames[{len(loop_list)}] = {{")
        out.append(",\n".join(f"  {state}_loop_f{i}" for i in range(len(loop_list))))
        out.append("};")
        out.append(f"const uint16_t {state}_loop_sizes[{len(loop_list)}] = {{")
        out.append("  " + ", ".join(str(len(f)) for f in loop_list))
        out.append("};")
        out.append("")


def main() -> None:
    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    states = list(crab_data.ANIMATIONS.keys())
    order = ["T", "W", "D", "E", "I"]
    states = [s for s in order if s in states] + [s for s in states if s not in order]

    # ── 1. 生成 crab_data.h（小头文件） ──
    h_lines = []
    h_lines.append("// AUTO-GENERATED by build_h.py — DO NOT EDIT")
    h_lines.append("// 由 tools/build/crab_data.py 转换而来")
    h_lines.append("#pragma once")
    h_lines.append("")
    h_lines.append("#include <stdint.h>")
    h_lines.append("#include <stddef.h>")
    h_lines.append("")
    h_lines.append(f"#define CRAB_FRAME_W      {crab_data.FRAME_W}")
    h_lines.append(f"#define CRAB_FRAME_H      {crab_data.FRAME_H}")
    h_lines.append(f"#define CRAB_FPS          {crab_data.FPS}")
    h_lines.append(f"#define CRAB_MS_PER_FRAME {crab_data.MS_PER_FRAME}")
    h_lines.append("")

    h_lines.append("typedef struct {")
    h_lines.append("  char id;                          // 'T' 'W' 'D' 'E' 'I'")
    h_lines.append("  const uint8_t* palette;           // 512B = 256 色 RGB565 (大端)")
    h_lines.append("  uint16_t intro_count;             // intro 段帧数，0 表示无 intro")
    h_lines.append("  const uint8_t* const* intro_frames;")
    h_lines.append("  const uint16_t* intro_sizes;")
    h_lines.append("  uint16_t loop_count;              // loop 段帧数")
    h_lines.append("  const uint8_t* const* loop_frames;")
    h_lines.append("  const uint16_t* loop_sizes;")
    h_lines.append("} CrabState;")
    h_lines.append("")

    # extern 声明所有数据数组
    h_lines.append("// 调色板（512B 大端 RGB565）")
    for s in states:
        h_lines.append(f"extern const uint8_t {s}_palette[512];")
    h_lines.append("")
    h_lines.append("// intro 帧指针 + 长度数组")
    for s in states:
        data = crab_data.ANIMATIONS[s]
        if data.get("intro"):
            n = len(data["intro"])
            h_lines.append(f"extern const uint8_t* const {s}_intro_frames[{n}];")
            h_lines.append(f"extern const uint16_t {s}_intro_sizes[{n}];")
    h_lines.append("")
    h_lines.append("// loop 帧指针 + 长度数组")
    for s in states:
        data = crab_data.ANIMATIONS[s]
        if data.get("loop"):
            n = len(data["loop"])
            h_lines.append(f"extern const uint8_t* const {s}_loop_frames[{n}];")
            h_lines.append(f"extern const uint16_t {s}_loop_sizes[{n}];")
    h_lines.append("")

    h_lines.append(f"#define CRAB_STATE_COUNT {len(states)}")
    h_lines.append("extern const CrabState CRAB_STATES[CRAB_STATE_COUNT];")
    h_lines.append("")

    h_lines.append("static inline const CrabState* crab_get_state(char c) {")
    h_lines.append("  for (int i = 0; i < CRAB_STATE_COUNT; i++) {")
    h_lines.append("    if (CRAB_STATES[i].id == c) return &CRAB_STATES[i];")
    h_lines.append("  }")
    h_lines.append("  return NULL;")
    h_lines.append("}")

    OUT_H.write_text("\n".join(h_lines) + "\n", encoding="utf-8")

    # ── 2. 生成 crab_data.c（大数据文件） ──
    c_lines = []
    c_lines.append("// AUTO-GENERATED by build_h.py — DO NOT EDIT")
    c_lines.append('#include "crab_data.h"')
    c_lines.append("")

    for s in states:
        emit_state_data(s, crab_data.ANIMATIONS[s], c_lines)

    # 总表
    c_lines.append("const CrabState CRAB_STATES[CRAB_STATE_COUNT] = {")
    for s in states:
        data = crab_data.ANIMATIONS[s]
        intro_list = data.get("intro", [])
        loop_list  = data.get("loop", [])
        intro_ptr  = f"{s}_intro_frames" if intro_list else "NULL"
        intro_sz   = f"{s}_intro_sizes"  if intro_list else "NULL"
        loop_ptr   = f"{s}_loop_frames"  if loop_list  else "NULL"
        loop_sz    = f"{s}_loop_sizes"   if loop_list  else "NULL"
        c_lines.append(f"  {{ '{s}', {s}_palette, "
                     f"{len(intro_list)}, {intro_ptr}, {intro_sz}, "
                     f"{len(loop_list)}, {loop_ptr}, {loop_sz} }},")
    c_lines.append("};")

    OUT_C.write_text("\n".join(c_lines) + "\n", encoding="utf-8")

    size_h_kb = OUT_H.stat().st_size / 1024
    size_c_kb = OUT_C.stat().st_size / 1024
    print(f"[OK] 生成 {OUT_H}  ({size_h_kb:.1f} KB)")
    print(f"     {OUT_C}  ({size_c_kb:.1f} KB)")
    print(f"     状态：{states}")


if __name__ == "__main__":
    main()
